### ISSUE TITLE
Request for saga middleware

### ISSUE THREAD

**Issue by benzsuankularb** [mattak/Unidux#126]
Request for saga middleware

with Put, Call, TakeLast, TakeAll, TakeFirst

**Comment by mattak** [comment]
@benzsuankularb

Thanks for suggestion!

Sorry, I don't know much about saga. 😭 
If you want to use saga like as asynchronous feature, maybe UniRx is on your request.

Sadly, Unidux don't have a plan to create saga middleware at least on this repository.
But I can help you if you want to create saga style middleware on your own.
