### ISSUE TITLE
ScriptTemplates is not included in the latest unitypackage

### ISSUE THREAD

**Issue by kn1cht** [mattak/Unidux#135]
I installed `v0.3.3` and found that any script templates wasn't added to the create menu.
Is this intended?

↓`v0.3.1`
<img src="https://user-images.githubusercontent.com/16277200/46518692-6ccd6700-c8b0-11e8-89e8-d260aec873d6.PNG" width=300px>

↓`v0.3.3`
<img src="https://user-images.githubusercontent.com/16277200/46518693-6dfe9400-c8b0-11e8-9a91-fd837155d926.PNG" width=300px>

**Comment by mattak** [comment]
@kn1cht Sorry for late response 🙏  Now the fix is included in 0.3.4! 🎉 
https://github.com/mattak/Unidux/releases/tag/0.3.4
