### ISSUE TITLE
Run test on CI

### ISSUE THREAD

**Issue by mattak** [mattak/Unidux#41]
Investigate how to run UnityC# test on CI and support it.

**Comment by mattak** [comment]
Great example
- https://github.com/SebastianJay/unity-ci-test

**Comment by haraldreingruber** [comment]
I would be interested in contributing this improvement. Is it still of interest?

My Idea would be to run it on Circle CI using this Unity3d Docker Image: https://hub.docker.com/r/gableroux/unity3d

https://github.com/neuecc/UniRx is doing something similar.

**Comment by mattak** [comment]
@haraldreingruber 

Thanks for your suggestion! 
It's great to support Circle CI using Unity3d Docker image for testing.
If you have interested in supporting Circle CI, pull request is always welcome! 😆

**Comment by haraldreingruber** [comment]
@mattak I started looking into it.

I get a build error because of the UniRx dependencies.
I saw that it is integrated as a submodule... but it's not inside the Assets folder of Unidux. I guess this is because it's not shipped with the library? Do you copy it manually, when running the tests on your machine?

**Comment by mattak** [comment]
@haraldreingruber

Thanks for your contribution! ✨

No, I don't copy UniRx files manually.
Unidux has UniRx symbolic link which located under `Assets/Plugins/` folder.

- https://github.com/mattak/Unidux/blob/master/Assets/Plugins/UniRx

There are no need to copy UniRx files, what you need to do is just `git submodule update --init`.


## setup details


### 1. clone & submoule init

```
git clone git@github.com:mattak/Unidux.git
cd Unidux
git submodule update --init
```

### 2. open project by Unity

### 3a. open test runner tab & run EditMode test

![image](https://user-images.githubusercontent.com/522828/69060874-7df91900-0a5b-11ea-892f-7b10568b2b1b.png)

### 3b. or run batchmode test on command line.

```
/Applications/Unity_2019.2.12f1/Unity.app/Contents/MacOS/Unity -runEditorTests -batchmode -projectPath `pwd` -nographics -editorTestsResultFile `pwd`/result.xml
```

**Comment by haraldreingruber** [comment]
@mattak Okay great, have to check, maybe the symbolic link didn't work on Windows... afaik git handles symbolic links on Windows as well, but maybe there are problems in some scenarios.

Let you know when I have more insights.

**Comment by mattak** [comment]
@haraldreingruber 
Sorry I cannot try to check how git and symlink work on windows, because I always use MacOS.
By the way, it looks like Circle CI is supporting Linux/Windows for free environment and docker instance is basically running on linux.
I'll check how can I run testing on Linux docker instance and check circle ci configuration of UniRx.

Thanks!

**Comment by mattak** [comment]
outdated.
