### ISSUE TITLE
Keep up the good work

### ISSUE THREAD

**Issue by austinmao** [mattak/Unidux#48]

**Comment by austinmao** [comment]
I just wanted you to know that I appreciate this repo and your hard work! :)

**Comment by mattak** [comment]
Thank you! I keep working

**Comment by austinmao** [comment]
Is there any way to communicate with you other than this comment board?

**Comment by mattak** [comment]
OK!
I prepared gitter room. you can join it. (it's public)
- https://gitter.im/Unidux/Lobby

or mail me to `mattak.me@gmail.com`
