### ISSUE TITLE
Suggestion: Adopt Ducks proposal for easier organization of reducers and actions

### ISSUE THREAD

**Issue by austinmao** [mattak/Unidux#49]
See https://github.com/erikras/ducks-modular-redux
Counter example: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/modules/counter.js

I found this to be a much easier method of organizing reducers and actions. It also made it easier to share component actions with other developers since it was all centralized in one place.

**Comment by mattak** [comment]
@austinmao 
It seems nice rule!
I read the document and try to apply the ducks proposal to `Example/{Counter,List}`.

Would you check #50 is correct for ducks rule?

- https://github.com/mattak/Unidux/pull/50/files

If the pull request is ok, I'll merge it!

**Comment by mattak** [comment]
#50 was merged!
